server:
  port: 8085

#spring:
    #datasource:
        #name: test21
        #url: jdbc:mysql://47.102.106.153:3306/study?characterEncoding=UTF-8
        #username: *
        #password: *
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: com.mysql.jdbc.Driver
        #filters: stat
        #maxActive: 20
        #initialSize: 1
        #maxWait: 60000
        #minIdle: 1
        #timeBetweenEvictionRunsMillis: 60000
        #minEvictableIdleTimeMillis: 300000
        #validationQuery: select 'x'
        #testWhileIdle: true
        #testOnBorrow: false
        #testOnReturn: false
        #poolPreparedStatements: true
        #maxOpenPreparedStatements: 20

## MySQL 读写分离
spring:
  datasource:
    master:
      url: jdbc:mysql://47.102.106.153:3306/study?characterEncoding=utf8
      username: root
      password: admin
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

    slave1:
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8
      username: root
      password: 123456
      # 使用druid数据源
      #type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20


    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        mode: HTML5


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hohe.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

quartz:
    enabled: true

#activemq
activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool.enabled: false
